#!/bin/bash
docker pull docker.io/busybox &
docker pull docker.io/eformat/welcome &
docker pull docker.io/openshift/jenkins-1-centos7 &
docker pull docker.io/openshift/nodejs-010-centos7 &
docker pull registry.access.redhat.com/jboss-eap-6/eap64-openshift &
docker pull registry.access.redhat.com/jboss-eap-6/eap64-openshift:1.2 &
docker pull registry.access.redhat.com/jboss-webserver-3/webserver30-tomcat8-openshift &
docker pull registry.access.redhat.com/openshift3/metrics-cassandra &
docker pull registry.access.redhat.com/openshift3/metrics-deployer &
docker pull registry.access.redhat.com/openshift3/metrics-hawkular-metrics &
docker pull registry.access.redhat.com/openshift3/metrics-heapster &
docker pull registry.access.redhat.com/openshift3/mysql-55-rhel7 &
docker pull registry.access.redhat.com/openshift3/nodejs-010-rhel7 &
docker pull registry.access.redhat.com/openshift3/ose-deployer &
docker pull registry.access.redhat.com/openshift3/ose-docker-builder &
docker pull registry.access.redhat.com/openshift3/ose-docker-registry &
docker pull registry.access.redhat.com/openshift3/ose-haproxy-router &
docker pull registry.access.redhat.com/openshift3/ose-pod &
docker pull registry.access.redhat.com/openshift3/ose-sti-builder &
docker pull registry.access.redhat.com/openshift3/php-55-rhel7 &
docker pull registry.access.redhat.com/openshift3/ruby-20-rhel7 &
docker pull registry.access.redhat.com/rhscl/perl-520-rhel7 &
docker pull registry.access.redhat.com/rhscl/php-56-rhel7 &
docker pull registry.access.redhat.com/openshift3/logging-elasticsearch &
docker pull registry.access.redhat.com/openshift3/logging-fluentd &
docker pull registry.access.redhat.com/openshift3/logging-kibana &
docker pull registry.access.redhat.com/openshift3/logging-auth-proxy &
docker pull registry.access.redhat.com/rhscl/mongodb-26-rhel7 &
docker pull gcr.io/google_containers/spark:1.5.2_v1 &
docker pull gcr.io/google_containers/zeppelin:v0.5.6_v1 &
